# Generated by Django 5.1.4 on 2025-01-13 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_review_stars_alter_movie_duration_alter_review_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='movies',
            field=models.ManyToManyField(related_name='directors', to='movie_app.movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directed_movies', to='movie_app.director'),
        ),
    ]
