# Generated by Django 5.1.4 on 2025-01-13 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_director_movies_alter_movie_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='movies',
        ),
    ]
